name: Deploy Github Action

on:
  workflow_dispatch:

jobs:

  build:
    env:
      GITHUB_USER: "krankenbro"
  
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Run the actions/checkout
      uses: actions/checkout@v2
      
    - name: vc-module-image-tools
      uses: MikeHamilton-RW/deploy-common-actions@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        USER: ${{ env.GITHUB_USER }}
        REPOSITORY: "vc-module-image-tools"
        DEVELOPMENT_BRANCH: "dev"
        COMMIT_MESSAGE: "Deploy new Github Action"
        GHA_DEPLOY_BRANCH_NAME: "dev-workflow"

    - name: vc-module-pricing
      uses: MikeHamilton-RW/deploy-common-actions@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        USER: ${{ env.GITHUB_USER }}
        REPOSITORY: "vc-module-pricing"
        DEVELOPMENT_BRANCH: "dev"
        COMMIT_MESSAGE: "Deploy new Github Action"
        GHA_DEPLOY_BRANCH_NAME: "dev-workflow"